export const API_URL = process.env.REACT_APP_API_URL

export const USER_TYPE_SCHOOL_ADMIN = 'SCHOOL_ADMIN'
export const USER_TYPE_SCHOOL_SUB_ADMIN = 'SCHOOL_SUB_ADMIN'
export const USER_TYPE_SUPER_ADMIN = 'SUPER_ADMIN'
export const USER_TYPE_TEACHER = 'TEACHER'
export const USER_TYPE_STUDENT = 'STUDENT'

export const STATUS_NOT_YET_STARTED = 'NOT_YET_STARTED'
export const STATUS_ON_GOING = 'ON_GOING'
export const STATUS_FOR_CHECKING = 'FOR_CHECKING'
export const STATUS_COMPLETED = 'COMPLETED'

export const STATUS_MODULE_NOT_YET_STARTED = 'NOT_YET_STARTED'
export const STATUS_MODULE_IN_PROGRESS = 'IN_PROGRESS'
export const STATUS_MODULE_DONE = 'DONE'
